DROP DATABASE IF EXISTS essence;
CREATE DATABASE IF NOT EXISTS essence;

USE essence;

CREATE TABLE IF NOT EXISTS users (
    userId BIGINT(11) NOT NULL AUTO_INCREMENT,
    fullname VARCHAR(50) NOT NULL DEFAULT "",
    email VARCHAR(50) NOT NULL DEFAULT "",
    username VARCHAR(50) NOT NULL DEFAULT "",
    password VARCHAR(60) NOT NULL DEFAULT "",
    dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    dateUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (userId),
    UNIQUE KEY (email),
    UNIQUE KEY (username)
);


CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    dateUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT(11) NOT NULL AUTO_INCREMENT,
    user_id BIGINT(11) NOT NULL,
    order_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    total_amount DECIMAL(10, 2) NOT NULL,
    dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    dateUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (order_id),
    FOREIGN KEY (user_id) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id BIGINT(11) NOT NULL AUTO_INCREMENT,
    order_id BIGINT(11) NOT NULL,
    product_id BIGINT(11) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    dateUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (order_item_id),
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);


